"""
Mara event-response loop — drains the watcher queue and pushes raw events
to connected SSE clients. The AI reply is generated by the frontend calling
POST /v1/events/handle with the active conversation context.

Quiet hours: if the current local time falls within the configured window,
events are dropped silently (not queued for SSE).
"""
from __future__ import annotations

import asyncio
import logging
from datetime import datetime, time

from .watcher import EventItem, WatcherRegistry

log = logging.getLogger(__name__)

# SSE push: set of queues, one per connected /v1/notifications client
_sse_clients: set[asyncio.Queue] = set()


def add_sse_client(q: asyncio.Queue) -> None:
    _sse_clients.add(q)


def remove_sse_client(q: asyncio.Queue) -> None:
    _sse_clients.discard(q)


def _is_quiet_hours() -> bool:
    """Return True if the current local time is within the quiet hours window."""
    try:
        from ..database import shared_connection, get_setting
        conn = shared_connection()
        start_raw = get_setting(conn, "quiet_hours_start")
        end_raw = get_setting(conn, "quiet_hours_end")
        if start_raw is None or end_raw is None:
            return False
        enabled_raw = get_setting(conn, "quiet_hours_enabled")
        if enabled_raw == "0":
            return False
        start = time.fromisoformat(start_raw)
        end = time.fromisoformat(end_raw)
        now = datetime.now().time()
        # Handle overnight window (e.g. 21:00 – 07:00)
        if start <= end:
            return start <= now < end
        else:
            return now >= start or now < end
    except Exception:
        return False


def _push_to_clients(payload: dict) -> None:
    dead = set()
    for q in _sse_clients:
        try:
            q.put_nowait(payload)
        except asyncio.QueueFull:
            dead.add(q)
    _sse_clients.difference_update(dead)


async def run_response_loop(registry: WatcherRegistry, _system_prompt_getter=None) -> None:
    """Drain the event queue and forward each event to SSE clients."""
    while True:
        event = await registry.queue.get()
        try:
            if _is_quiet_hours():
                log.info("Quiet hours active — suppressing event: %s", event.title)
            else:
                _push_to_clients({
                    "type": "event",
                    "id": event.id,
                    "watcher_id": event.watcher_id,
                    "watcher_name": event.watcher_name,
                    "title": event.title,
                    "body": event.body,
                    "fired_at": event.fired_at,
                })
        except Exception:
            pass
        finally:
            registry.queue.task_done()
